# Generated by Django 3.0.6 on 2020-05-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angebot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=255)),
                ('firma', models.CharField(max_length=255)),
                ('anzeige', models.FileField(upload_to='anzeigen/%Y/%m/%d')),
                ('vorlage', models.CharField(choices=[('C', 'C'), ('JA', 'Java'), ('PE', 'Perl'), ('PY', 'Python'), ('RE', 'Redaktion')], max_length=10)),
                ('pub_date', models.DateTimeField(verbose_name='Veröffentlichung')),
                ('ansprechpartner', models.CharField(default='unbekannt', max_length=255)),
                ('anrede', models.CharField(default='unbekannt', max_length=16)),
                ('strasse', models.CharField(default='unbekannt', max_length=128, verbose_name='Straße')),
                ('hausnummer', models.IntegerField()),
                ('plz', models.CharField(default='unbekannt', max_length=5, verbose_name='PLZ')),
                ('ort', models.CharField(default='unbekannt', max_length=255)),
                ('telefon', models.CharField(default='unbekannt', max_length=32, verbose_name='Telefon (Festnetz)')),
                ('mobiltelefon', models.CharField(default='unbekannt', max_length=32)),
                ('email', models.CharField(default='unbekannt', max_length=32, verbose_name='E-Mail')),
                ('quelle', models.CharField(default='unbekannt', max_length=128)),
                ('website', models.CharField(default='unbekannt', max_length=64, verbose_name='Webseite')),
                ('ergebnis', models.TextField(default='steht noch aus', max_length=1024)),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
            },
        ),
    ]
